name: Docker CI

# Controls when the action will run.
on:
  pull_request:

jobs:
  # Start a Docker database container.
  start-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start database container
        run: docker-compose -f src/test/resources/docker/docker-compose.yml up -d

      - name: Setup Temurin Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      # Build the code using Maven
      - name: Build with Maven
        run: mvn -B jacoco:prepare-agent package --file pom.xml

      # Run the LiquibaseHarnessSuiteIT tests using Maven
      - name: Run Test Harness Tests
        run: mvn -B jacoco:prepare-agent surefire:test -Dit.test=LiquibaseHarnessSuiteIT

      - name: Stop database container
        run: docker stop yugabyte-container
