name: Liquibas Test Harness (Docker)

on:
  pull_request:

jobs:
  liquibaset-test-harness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start database container
        run: docker-compose -f src/test/resources/docker/docker-compose.yml up -d

      - name: Setup Temurin Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Build with Maven
        run: mvn -ntp -Dmaven.test.skip package

      - name: Run Base Liquibase Test Harness
        continue-on-error: true
        run: mvn -ntp -Dtest=ExtensionHarnessTest test

      - name: Run Foundational Liquibase Test Harness
        continue-on-error: true
        run: mvn -ntp -Dtest=LiquibaseHarnessFoundationalSuiteTest test

      - name: Run Advanced Liquibase Test Harness
        continue-on-error: true
        run: mvn -ntp -Dtest=LiquibaseHarnessAdvancedSuiteTest test

      - name: Stop database container
        run: docker-compose -f src/test/resources/docker/docker-compose.yml down
