name: Liquibase Test Harness

on:
  pull_request:

jobs:
  liquibaset-test-harness:
    name: Liquibase Test Harness
    runs-on: ubuntu-latest

    strategy:
      matrix:
        liquibase-support-level: [Base, Foundational, Advanced]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start database container
        run: docker-compose -f src/test/resources/docker/docker-compose.yml up -d

      - name: Setup Temurin Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Build with Maven
        run: mvn -ntp -Dmaven.test.skip package

      - name: Run ${{ matrix.liquibase-support-level }} Liquibase Test Harness
        continue-on-error: true
        run: mvn -ntp -Dtest=${{ matrix.liquibase-support-level }}ExtensionHarnessSuite test

      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
        continue-on-error: true
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Liquibase Test Harness - ${{ matrix.liquibase-support-level }} Reports            # Name of the check run which will be created
          path: target/surefire-reports/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results
          fail-on-error: false

      - name: Stop database container
        run: docker-compose -f src/test/resources/docker/docker-compose.yml down
